#What happens when „1‟== 1 is executed?

try:
   
    print('hello' == 1)
    
except Exception as e:
    print(e)